# Generated by Django 4.2.3 on 2023-08-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'permissions': [('can_create_gym', 'can create new gym'), ('can_edit_gym', 'can edit the gym info'), ('can_delete_gym', 'can delete the gym')]},
        ),
    ]
