# Generated by Django 4.2.3 on 2023-07-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
