# Generated by Django 4.2.3 on 2023-07-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuser',
            options={'permissions': [('can_create_staff', 'Can create staff accounts.'), ('can_create_user', 'Can create all kinds of accounts.')]},
        ),
    ]
